return {
  "folke/which-key.nvim",
  event = "VimEnter", -- Sets the loading event to 'VimEnter'
  config = function() -- This is the function that runs, AFTER loading
    require("which-key").setup()

    -- Dcument existing key chains
    require("which-key").register({
      -- { "", group = "[D]ebug" },
      -- { "", group = "[F]ind" },
      -- { "", group = "[U]I" },
      -- { "", group = "[R]ename" },
      -- { "", group = "[E]xplorer" },
      -- { "", group = "D[A]shboard" },
      -- { "", group = "[M]ason" },
      -- { "", group = "[X]trouble" },
      -- { "", group = "[L]azy" },
      -- { "", group = "[T]est" },
      -- { "", group = "[L]anguage Tools" },
      -- { "", group = "[C]ode" },
      -- { "", group = "[O]bsidian" },
      -- { "", group = "Leet[K]ode" },
      -- { "", group = "[G]it" },
      -- { "", group = "[H]arpoon" },
      -- { "", group = "[B]uffer" },
      -- { "", desc = "",                 hidden = true, mode = { "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n", "n" } },
      -- { "", desc = "<leader>x_",       hidden = true },
      -- { "", desc = "<leader>h_",       hidden = true },
      -- { "", group = "Leet[K]ode" },
      -- { "", desc = "<leader>k_",       hidden = true },
      -- { "", group = "[H]arpoon" },
      -- { "", group = "[G]it" },
      -- { "", desc = "<leader>g_",       hidden = true },
      -- { "", desc = "<leader>f_",       hidden = true },
      -- { "", group = "[L]anguage Tools" },
      -- { "", group = "[O]bsidian" },
      -- { "", group = "[T]est" },
      -- { "", desc = "<leader>t_",       hidden = true },
      -- { "", desc = "<leader>l_",       hidden = true },
      -- { "", desc = "<leader>r_",       hidden = true },
      -- { "", desc = "<leader>o_",       hidden = true },
      -- { "", group = "[R]ename" },
      -- { "", group = "[U]I" },
      -- { "", group = "[F]ind" },
      -- { "", group = "[E]xplorer" },
      -- { "", group = "[M]ason" },
      -- { "", desc = "<leader>M_",       hidden = true },
      -- { "", group = "D[A]shboard" },
      -- { "", desc = "<leader>L_",       hidden = true },
      -- { "", group = "[X]trouble" },
      -- { "", group = "[L]azy" },
      -- { "", desc = "<leader>e_",       hidden = true },
      -- { "", desc = "<leader>a_",       hidden = true },
      -- { "", desc = "<leader>b_",       hidden = true },
      -- { "", desc = "<leader>d_",       hidden = true },
      -- { "", group = "[B]uffer" },
      -- { "", group = "[D]ebug" },
      -- { "", group = "[C]ode" },
      -- { "", desc = "<leader>c_",       hidden = true },
      -- { "", desc = "<leader>u_",       hidden = true },
      -- { "<leader>L",  group = "[L]azy" },
      -- { "<leader>L_", hidden = true },
      -- { "<leader>M",  group = "[M]ason" },
      -- { "<leader>M_", hidden = true },
      -- { "<leader>a",  group = "D[A]shboard" },
      -- { "<leader>a_", hidden = true },
      -- { "<leader>b",  group = "[B]uffer" },
      -- { "<leader>b_", hidden = true },
      -- { "<leader>c",  group = "[C]ode" },
      -- { "<leader>c_", hidden = true },
      -- { "<leader>d",  group = "[D]ebug" },
      -- { "<leader>d_", hidden = true },
      -- { "<leader>e",  group = "[E]xplorer" },
      -- { "<leader>e_", hidden = true },
      -- { "<leader>f",  group = "[F]ind" },
      -- { "<leader>f_", hidden = true },
      -- { "<leader>g",  group = "[G]it" },
      -- { "<leader>g_", hidden = true },
      -- { "<leader>h",  group = "[H]arpoon" },
      -- { "<leader>h_", hidden = true },
      -- { "<leader>k",  group = "Leet[K]ode" },
      -- { "<leader>k_", hidden = true },
      -- { "<leader>l",  group = "[L]anguage Tools" },
      -- { "<leader>l_", hidden = true },
      -- { "<leader>o",  group = "[O]bsidian" },
      -- { "<leader>o_", hidden = true },
      -- { "<leader>r",  group = "[R]ename" },
      -- { "<leader>r_", hidden = true },
      -- { "<leader>t",  group = "[T]est" },
      -- { "<leader>t_", hidden = true },
      -- { "<leader>u",  group = "[U]I" },
      -- { "<leader>u_", hidden = true },
      -- { "<leader>x",  group = "[X]trouble" },
      -- { "<leader>x_", hidden = true },
      ["<leader>a"] = { name = "D[A]shboard", _ = "which_key_ignore" },
      ["<leader>b"] = { name = "[B]uffer", _ = "which_key_ignore" },
      ["<leader>c"] = { name = "[C]ode", _ = "which_key_ignore" },
      ["<leader>d"] = { name = "[D]ebug", _ = "which_key_ignore" },
      ["<leader>e"] = { name = "[E]xplorer", _ = "which_key_ignore" },
      ["<leader>f"] = { name = "[F]ind", _ = "which_key_ignore" },
      ["<leader>g"] = { name = "[G]it", _ = "which_key_ignore" },
      ["<leader>h"] = { name = "[H]arpoon", _ = "which_key_ignore" },
      ["<leader>k"] = { name = "Leet[K]ode", _ = "which_key_ignore" },
      ["<leader>l"] = { name = "[L]anguage Tools", _ = "which_key_ignore" },
      ["<leader>L"] = { name = "[L]azy", _ = "which_key_ignore" },
      ["<leader>M"] = { name = "[M]ason", _ = "which_key_ignore" },
      ["<leader>o"] = { name = "[O]bsidian", _ = "which_key_ignore" },
      ["<leader>r"] = { name = "[R]ename", _ = "which_key_ignore" },
      ["<leader>t"] = { name = "[T]est", _ = "which_key_ignore" },
      ["<leader>u"] = { name = "[U]I", _ = "which_key_ignore" },
      ["<leader>x"] = { name = "[X]trouble", _ = "which_key_ignore" },
    })
  end,
}
